### ISSUE TITLE
Multiple minor issues

### ISSUE THREAD

**Issue by DavidVentura** [nergdron/dve#3]
Hi

I don't want to create a PR because most of my code is specific to what I need so I'll detail here what I think you should change.

* set the -e flag for bash, if you have an error, you don't want to continue encoding on broken/incomplete files.
* Use the "local" server defined by GNU Parallel ":" [Link] (http://www.gnu.org/software/parallel/parallel_tutorial.html#Remote-execution)
* Don't force the same absolute path for ffmpeg on every server; trust $PATH to be right. My servers have correctly set their $PATH, but some have ffmpeg on /usr/bin, some on /usr/local/bin, etc. The checkpath function forces them to run the on the exact same path.
* create proper PTS on AVI files [Info] (https://trac.ffmpeg.org/ticket/3339) [More info] (https://trac.ffmpeg.org/ticket/1552), and check for errors when generating the segments. ffmpeg may exit with non-zero status and may not generate the requested output files.

```bash
if [[ "$1" == *".AVI" ]]; then
       $ENCPATH -fflags +genpts -i "$1"  -map 0 -codec copy -f segment -segment_time $LEN -segment_format matroska -v ${VERBOSE} "${OUTDIR}/chunk-%03d.orig"
else
       $ENCPATH -i "$1"  -map 0 -codec copy -f segment -segment_time $LEN -segment_format matroska -v ${VERBOSE} "${OUTDIR}/chunk-%03d.orig"
fi

#also check for errors here
if [ $? -ne 0 ]; then
       echo "Error creating chunks "
       exit
fi
```

That's it

Edit: You can look at my fork if you want, it has these changes

**Comment by nergdron** [comment]
Hi David, thanks for the feedback!

- The reason I hadn't set -e is because if it breaks partway through, you can get left with a potentially very large temporary directory full of video chunks that doesn't get cleaned up, and this can break subsequent runs in certain edge cases. I think you're probably right that default behaviour should be to stop on error though.
- Do you mean just as a replacement default in SERVERS="localhost"? Or was there another reason / place to use this?
- I think you're right about the PATH stuff, I got a little lazy in cleaning up a previous code revision which mucked around with multiple versions of ffmpeg due to the Debian package mess. But that's been resolved, and I didn't make this as clean as it could be.
- I actually don't have any AVI files, so I never thought about this problem or tested it. Seems sensible to handle this for AVIs, so I'll look into getting it sorted.

**Comment by nergdron** [comment]
Just did a commit that I think should fix most of the things you brought up, if not all of them. Please take a look and test, make sure the AVI stuff especially is behaving as you expect, since I only did cursory testing there. Also, I noticed your branch has some custom encoding settings, so I just added a quick little thing to source a ~/.dverc file if present, so you don't have to modify the script source to change any of the defaults in your setup. I'll probably rename the variables used to something more sensible and consistent with the app, as well as provide an example file at some point, but I thought I'd get your feedback first on the outstanding stuff on this ticket.

**Comment by DavidVentura** [comment]
Awesome.

* To set -e and handle it properly, you can always trap exit
```bash
~$ ./test.sh
cat: fake-file: No such file or directory
exiting
david@homeserver:~$ cat test.sh
#!/bin/bash -e
function finish {
        echo "exiting"
#here you'd rm -rf ~/.dve/
}
trap finish EXIT
cat fake-file
echo "this won't print"
```

* Yes, I meant : as a replacement for localhost, to avoid using ssh locally (and copying the files again!)

The rest seems okay (thanks for the .dverc file I'll rebase my fork)
