### ISSUE TITLE
720p? 

### ISSUE THREAD

**Issue by scorpio2k2** [nergdron/dve#6]
hi,

what if I need to transcode files to 720p?

**Comment by nergdron** [comment]
Hey,

You can specify whatever other video encoding options you want for ffmpeg by using the -o option to override the default encoding settings. The ffmpeg docs should have info on how to do video resizing as part of the encoding process.

**Comment by scorpio2k2** [comment]
I need to export to mp4 not mkv...

**Comment by nergdron** [comment]
Well that's a different problem then. Currently I'm defaulting to mkv because the muxing of the chunks and attachments works the best with open source tools. You can see on line 107 where it specifies the output format, so you can change it to mp4 there and see if it works for you, but I can't guarantee it'll work correctly with all input media types.

**Comment by scorpio2k2** [comment]
I'll try . In input I have files with xdcam HD 422 50mbps and DVCPRO HD ..
